[project]
name = "mlops-loan-pred"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=24.10.0",
    "click>=8.1.8",
    "pandas>=2.2.3",
    "pylint>=3.3.3",
    "scikit-learn>=1.6.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
